// License signing core: Ed25519 keypair (server keeps the private key,
// the app embeds only the public key). Zero dependencies.
const crypto = require('crypto')
const fs = require('fs')
const path = require('path')

const SECRETS_DIR = path.join(__dirname, '..', 'secrets')
const PRIVATE_FILE = path.join(SECRETS_DIR, 'private.pem')
const PUBLIC_FILE = path.join(SECRETS_DIR, 'public.pem')

// Embedded public key lives in the app repo (committed). The private key
// lives ONLY on the seller's machine / license server (gitignored).
const APP_PUBLIC_FILE = path.join(__dirname, '..', '..', 'src', 'kastraPublic.js')

function ensureKeys() {
  if (fs.existsSync(PRIVATE_FILE) && fs.existsSync(PUBLIC_FILE)) {
    return {
      privateKey: fs.readFileSync(PRIVATE_FILE, 'utf8'),
      publicKey: fs.readFileSync(PUBLIC_FILE, 'utf8')
    }
  }
  const { publicKey, privateKey } = crypto.generateKeyPairSync('ed25519')
  const pub = publicKey.export({ type: 'spki', format: 'pem' }).toString()
  const priv = privateKey.export({ type: 'pkcs8', format: 'pem' }).toString()
  fs.mkdirSync(SECRETS_DIR, { recursive: true })
  fs.writeFileSync(PRIVATE_FILE, priv, { mode: 0o600 })
  fs.writeFileSync(PUBLIC_FILE, pub)
  return { privateKey: priv, publicKey: pub }
}

// Keygen for the app: regenerate the embedded public key from the server's
// keypair. Run once per build machine via `npm run license:keygen`.
function embedPublicKey() {
  const keys = ensureKeys()
  const js = '// AUTO-GENERATED by `npm run license:keygen`. Do not hand-edit.\n' +
    'module.exports=' + JSON.stringify(keys.publicKey) + '\n'
  fs.writeFileSync(APP_PUBLIC_FILE, js)
  return APP_PUBLIC_FILE
}

function signPayload(payload, privateKeyPem) {
  const data = Buffer.from(JSON.stringify(payload), 'utf8')
  const sig = crypto.sign(null, data, privateKeyPem)
  return sig.toString('base64')
}

function verifyPayload(payload, sigB64, publicKeyPem) {
  try {
    const data = Buffer.from(JSON.stringify(payload), 'utf8')
    return crypto.verify(null, data, publicKeyPem, Buffer.from(sigB64, 'base64'))
  } catch {
    return false
  }
}

// Human-friendly license key: KAS-XXXX-XXXX-XXXX-XXXX
function makeLicenseKey() {
  const hex = crypto.randomBytes(8).toString('hex').toUpperCase()
  return 'KAS-' + hex.replace(/(....)/g, '$1-').replace(/-$/, '')
}

module.exports = { ensureKeys, embedPublicKey, signPayload, verifyPayload, makeLicenseKey, APP_PUBLIC_FILE, PRIVATE_FILE, PUBLIC_FILE }